#!/usr/bin/env python3

import sys

f1 = open(sys.argv[1])
f2 = open(sys.argv[2])

dict1 = {ur: sr for ur, sr in [line.split() for line in f1.readlines()]}
dict2 = {ur: sr for ur, sr in [line.split() for line in f2.readlines()]}

f1w = open(sys.argv[1], "w+")
f2w = open(sys.argv[2], "w+")
f3w = open(sys.argv[3], "a")

for k, v in dict1.items():
    if v != dict2[k]:
        f1w.write(k + "\t" + v + "\n")
        f2w.write(k + "\t" + dict2[k] + "\n")
    else:
        f3w.write(k + "\t" + v + "\n")
